package internal

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type migrationModule struct {
	name         string
	migrationDir string
	entityDir    string
}

type migrationKind string

const (
	migrationKindInit  migrationKind = "init"
	migrationKindAlter migrationKind = "alter"
)

type migrationFile struct {
	path      string
	baseName  string
	kind      migrationKind
	direction string
}

type migrationState struct {
	latest *migrationFile
}

func findModules() ([]migrationModule, error) {
	var modules []migrationModule

	// Finding project root
	root, err := FindRoot()
	if err != nil {
		return nil, err
	}

	// Resolving module path
	var modulesPath string
	if filepath.IsAbs(ModulesDir) {
		modulesPath = ModulesDir
	} else {
		modulesPath = filepath.Join(root, ModulesDir)
	}
	if _, err := os.Stat(modulesPath); errors.Is(err, os.ErrNotExist) {
		return nil, errors.New("module path is not found")
	}

	// Reading module directories
	entries, err := os.ReadDir(modulesPath)
	if err != nil {
		return nil, fmt.Errorf("read modules: %w", err)
	}
	for _, entry := range entries {
		// Only module directories can own migration/entity paths.
		if !entry.IsDir() {
			continue
		}

		modulePath := filepath.Join(modulesPath, entry.Name())
		migModule := migrationModule{
			name:         entry.Name(),
			migrationDir: filepath.Join(modulePath, "migration"),
			entityDir:    filepath.Join(modulePath, "internal", "domain", "entity"),
		}
		modules = append(modules, migModule)
	}

	return modules, nil
}

func entityNameFromFile(goName string) string {
	return strings.TrimSuffix(goName, filepath.Ext(goName))
}

func findEntityMigrationState(module migrationModule, entityName string) (migrationState, error) {
	// Reading migration directory
	entries, err := os.ReadDir(module.migrationDir)
	if err != nil {
		return migrationState{}, fmt.Errorf("read migration dir: %w", err)
	}

	// Finding latest migration state
	state := migrationState{}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}

		file, ok := parseMigrationFile(filepath.Join(module.migrationDir, entry.Name()), entityName)
		if !ok {
			continue
		}

		if state.latest == nil || file.baseName > state.latest.baseName {
			state.latest = file
			continue
		}

		if file.baseName == state.latest.baseName && file.direction == "up" {
			state.latest = file
		}
	}

	return state, nil
}

func parseMigrationFile(path string, entityName string) (*migrationFile, bool) {
	fileName := filepath.Base(path)

	var direction string
	var baseName string
	switch {
	case strings.HasSuffix(fileName, ".up.sql"):
		direction = "up"
		baseName = strings.TrimSuffix(fileName, ".up.sql")
	case strings.HasSuffix(fileName, ".down.sql"):
		direction = "down"
		baseName = strings.TrimSuffix(fileName, ".down.sql")
	default:
		return nil, false
	}

	// Split the sequence prefix from the migration descriptor.
	parts := strings.SplitN(baseName, "_", 2)
	if len(parts) != 2 {
		return nil, false
	}

	descriptor := parts[1]
	if !strings.HasSuffix(descriptor, "_"+entityName) {
		return nil, false
	}

	// Classify only the migration kinds generated by this package.
	switch {
	case descriptor == "init_"+entityName:
		return &migrationFile{
			path:      path,
			baseName:  baseName,
			kind:      migrationKindInit,
			direction: direction,
		}, true
	case strings.HasPrefix(descriptor, "alter_"):
		return &migrationFile{
			path:      path,
			baseName:  baseName,
			kind:      migrationKindAlter,
			direction: direction,
		}, true
	default:
		return nil, false
	}
}

func migrationFilePair(file migrationFile) (string, string) {
	dir := filepath.Dir(file.path)

	return filepath.Join(dir, file.baseName+".up.sql"), filepath.Join(dir, file.baseName+".down.sql")
}
